const PortfolioData = [
  {
    id: 1,
    category: "react.1",
    totalLike: "600",
    title: "portfolio1.1",
    image: "/assets/portfolio/proment.png",
    desc1: "portfolio1desc.1",
    desc2: "portfolio1desc2.1",
  },
  {
    id: 2,
    category: "flutter.1",
    totalLike: "750",
    title: "portfolio2.1",
    image: "/assets/portfolio/trivia.png",
    desc1: "portfolio2desc.1",
    desc2: "portfolio2desc2.1",
  },
  {
    id: 3,
    category: "react.1",
    totalLike: "630",
    title: "portfolio3.1",
    image: "/assets/portfolio/wifair.png",
    desc1: "portfolio3desc.1",
    desc2: "portfolio3desc2.1",
  },
  {
    id: 4,
    category: "both.1",
    totalLike: "360",
    title: "portfolio4.1",
    image: "/assets/portfolio/iniprojet.png",
    desc1: "portfolio4desc.1",
    desc2: "portfolio4desc2.1",
  },
  {
    id: 5,
    category: "both.1",
    totalLike: "280",
    title: "portfolio5.1",
    image: "/assets/portfolio/bssahtek.png",
    desc1: "portfolio5desc.1",
    desc2: "portfolio5desc2.1",
  },
  {
    id: 6,
    category: "flutter.1",
    totalLike: "690",
    title: "portfolio6.1",
    image: "/assets/portfolio/flutterapp.jpeg",
    desc1: "portfolio6desc.1",
    desc2: "portfolio6desc2.1",
  },
];
export default PortfolioData;
